name: Update Bluesky Feed
on:
  schedule: [{cron: "*/5 * * * *"}]
  workflow_dispatch:
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: "3.11"}
      - run: pip install -r requirements.txt
      - run: python scripts/fetch_bsky.py
      - run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/bluesky.json
          git diff --staged --quiet || git commit -m "chore: update bluesky feed"
          git push